### ISSUE TITLE
Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by florestankorp** [dscheerens/ngx-inject#6]
Hi Daan, we're trying to build an ng-packagr library after updating to Angular 10 and are getting this error.

```
An unhandled exception occurred: node_modules/ngx-inject/src/eager-provider-loading.d.ts:35:37 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

static for(provider: Provider): ModuleWithProviders;
```

I also found the link to the docs: [ModuleWithProviders Migration](https://angular.io/guide/migration-module-with-providers)

**Comment by dscheerens** [comment]
Hey Florestan, thought I already took care of that in the 2.0.0 release, but apparently not. Just [fixed it](https://github.com/dscheerens/ngx-inject/commit/6873dac30f713a3b68584a90b04b3e2f3d3dad74) and published the 3.0.0 release 😃
